# permissions for end users to edit registries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-editor-role
rules:
- apiGroups:
  - aws.com.ederium.ecr-credentials-controller
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.com.ederium.ecr-credentials-controller
  resources:
  - registries/status
  verbs:
  - get
